"""empty message

Revision ID: 324fc343b367
Revises: 6295d7b6a8ba
Create Date: 2025-05-07 17:09:22.577174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324fc343b367'
down_revision = '6295d7b6a8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('img', 'vid', name='mediatype'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
